### PR TITLE
React user lookup

### PR DESCRIPTION
**Pull request by LudwikJaniuk**
Using react in the user lookup page, giving us a nice, responsive search thingy. Reduced it to one search bar because zfinger has improved. Integrated babel to parse JSX in jade templates.

### CODE REVIEW

**Comment by macfeaster** [comment]
Are the React dependencies used minified?

**Comment by LudwikJaniuk** [comment]
Aight, fixat, tack.

**Comment by JSimo** [comment]
lgtm

**Comment by LudwikJaniuk** [comment]
Hm, är det adminkrav på user lookup?

**Comment by JSimo** [comment]
nej, men sidomenyn-renderingen vill veta om du är admin eller inte.

**Pull request merged**
